steps:
  # Сборка Docker образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-bot:latest', '.']
  
  # Отправка образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-bot:latest']
  
  # Деплой в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-bot:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'BOT_TOKEN=${_BOT_TOKEN},PROJECT_ID=${_PROJECT_ID},GOOGLE_APPLICATION_CREDENTIALS_JSON=${_GOOGLE_APPLICATION_CREDENTIALS_JSON},GOOGLE_SHEETS_CREDENTIALS_JSON=${_GOOGLE_SHEETS_CREDENTIALS_JSON},DEFAULT_MODEL=pro,GOOGLE_CLOUD_LOCATION=asia-southeast1,GEMINI_ANALYSIS_MODE=production'
      - '--service-account'
      - 'ai-bot-service-account@${_PROJECT_ID}.iam.gserviceaccount.com'

# Переменные для подстановки
substitutions:
  _BOT_TOKEN: '8291213805:AAEHDlkDCHLQ3RFtrB5HLMeU-nGzF1hOZYE'
  _PROJECT_ID: 'just-advice-470905-a3'
  # _GOOGLE_APPLICATION_CREDENTIALS_JSON будет передана через GitHub Secrets

# Опции сборки
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-bot:latest'
